### ISSUE TITLE
Update API docs for couple new endoints

### ISSUE THREAD

**Issue by treeder** [chainparency/docs#12]
```[tasklist]
### Tasks
- [x] How to post custom load fields (ie: the fields defined on asset)
- [x] How to upload an image to the feed
```

Using the new model.

**Comment by Bob1k** [comment]
@treeder, do you mean filling custom fields data in first task?

**Comment by treeder** [comment]
Commit: https://github.com/chainparency/docs/commit/f83a907aa5d6410b53551b829075bf7c8295a176
